spring:
  datasource:
    url: jdbc:h2:mem:coursereg;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop   # rebuild schema per test run
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

  flyway:
    enabled: false           # make sure Flyway doesn't run in tests

# If any web bits are hit in tests, randomize server port
server:
  port: 0
